-- Migration 004: Data for trains
-- Rows 1 to 129 of 129

PRAGMA foreign_keys = OFF;

BEGIN TRANSACTION;

INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (4, '1972 Mark 2 Stock', 4, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (5, 'Class 377/2 SN', 5, 'Class 377/2 SN');
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (38, 'ACS-64 V AMTK50', 38, 'ACS-64 V AMTK50');
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (39, 'Acela Express Amtrak', 39, 'Acela Express Amtrak');
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (40, 'CTC-3 MBTA', 40, 'CTC-3 MBTA');
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (41, 'F40PH-3C MBTA', 41, 'F40PH-3C MBTA');
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (62, 'LMS Jubilee', 62, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (75, 'TGV Duplex', 75, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (81, '1972 MkII Tube Stock LU', 81, '1972 MkII Tube Stock LU');
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (91, 'GP38-2 CN', 91, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (92, 'GP9RM CN', 92, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (113, 'LMS Stanier 8F', 113, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (123, 'Allegra 8/12 RhB', 123, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (124, 'Class 66 DB', 124, 'Class 66 DB');
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (131, 'EMD F125 Metrolink', 131, 'EMD F125 Metrolink');
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (132, 'Rotem Bi-Level Cab Car Metrolink', 132, 'Rotem Bi-Level Cab Car Metrolink');
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (146, 'Class 350/1', 146, 'Class 350/1');
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (150, 'Class 150/2 GWR', 150, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (157, 'Class 802', 157, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (162, 'Class 390', 162, 'Class 390');
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (163, 'Class 802/1 GWR', 157, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (164, 'HSP46 MBTA', 163, 'HSP46 MBTA');
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (165, 'Rotem CTC-5 MBTA', 164, 'Rotem CTC-5 MBTA');
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (166, 'ALP-46 NJT', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (167, 'Arrow III NJT', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (168, 'Multi-Level Commuter Cab Car NJT', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (169, 'BR 411 DB', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (170, 'BR185.5 MRCE', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (171, '766.2 DBpbzfa DB', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (172, 'BR 143 DB', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (173, 'BR 146.2 DB', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (174, 'BR 185.2 DB', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (175, 'BR 363 DBB', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (176, 'BR 442 Talent 2 DB', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (177, 'BR143 DB', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (178, 'Class 16', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (179, 'Class 66 EWS', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (180, 'HST FGB', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (181, 'Class 166 FGB', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (182, 'M3A MTA', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (183, 'M7A MTA', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (184, 'ES44AC NS', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (185, 'GP38-2 NS', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (186, 'Class 710 TFL', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (187, 'BR442 Talent 2', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (188, 'GP38-2 YN3b', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (189, 'AC4400CW YN3b', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (190, 'SD40 CSX-s', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (191, 'SD40-2 TTC', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (192, 'SD70ACe UP', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (193, 'SD40-2 UP', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (194, 'Class 09 GRN', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (195, 'Class 47 GRN', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (196, 'CTC-3 Cab Car', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (197, 'HST GWR', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (198, 'CSX GP38-2', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (199, 'MNR M7A', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (200, 'MNR M3A', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (201, 'EMD SD40-2', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (206, 'Metrolink F125', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (207, 'EMD F7', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (208, 'DB BR 103 + IC Coaches', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (209, 'DB BR 1442 Talent 2', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (210, 'DB BR 294', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (211, 'DB Freight Tankers', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (212, 'DB Car Transport', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (213, 'DB BR 642', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (214, 'DB BR 101 + IC Coaches', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (215, 'DB BR 363', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (216, 'DB BR 185', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (217, 'DB ICE-T', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (218, 'DB ICE 1', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (219, 'DB BR 143 + Dostos', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (220, 'DB BR 442 Talent 2', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (221, 'DB BR 612', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (222, 'DB BR 218', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (223, 'DB BR 146 + Dostos', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (224, 'RhB ABe 8/12 Allegra', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (225, 'London Underground 1972 Stock', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (226, 'BR Class 66', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (227, 'BR Class 47', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (228, 'DB BR 146', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (229, 'DB BR 193', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (230, 'BR Class 20', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (231, 'DB ICE 3M', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (232, 'BR Class 158', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (233, 'BR Class 37', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (234, 'BR Class 166 Networker Turbo', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (235, 'BR Class 150/2', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (236, 'BR Class 43 HST', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (237, 'BR Class 08', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (238, 'BR Class 377 Electrostar', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (239, 'BR Class 390 Pendolino', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (240, 'BR Class 350 Desiro', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (241, 'BR Class 710 Aventra', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (242, 'RhB Ge 4/4 II', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (243, 'DB BR 101', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (244, 'DB BR 110', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (245, 'DB BR 425', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (246, 'BR Class 153', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (247, 'BR Class 323', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (248, 'DB BR 423', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (249, 'DB BR 628', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (250, 'DB BR 430', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (251, 'SNCF TGV Duplex', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (252, 'BR Class 484', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (253, 'BR Class 483', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (254, 'DB BR 185 Intermodal', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (255, 'DB BR 111', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (256, 'LIRR M7', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (257, 'LIRR M3', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (258, 'CD Class 843', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (259, 'CD Class 854', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (260, 'BR Class 387 Electrostar', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (261, 'BR Class 375 Electrostar', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (262, 'BR Class 313', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (263, 'BR Class 465 Networker', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (264, 'SBB RABe 523', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (265, 'DB BR 365', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (266, 'DB BR 111 + n-Wagen', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (267, 'OBB 1020', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (268, 'OBB 1020 + n-Wagen', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (269, 'DB BR 111 + IC Coaches', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (270, 'Amtrak ACS-64', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (271, 'Acela Express', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (272, 'NJT ALP-46 + MultiLevel Coaches', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (273, 'Metrolink MP36PH-3C', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (274, '2 GWR', NULL, NULL);
INSERT INTO [trains] (id, name, class_id, in_game_name) VALUES (275, 'Class 20 DRU', NULL, NULL);

COMMIT;

PRAGMA foreign_keys = ON;
