"""Auto-generated test config — created by calibrate.py.

Imports everything from config.py, then overrides calibrated values
from 1_calibration.json so you can test without touching the original.
"""
from config import *  # noqa: F401,F403

# ── Calibration overrides ──
BOXES_PER_PAGE = 8
EXTRA_SECTION_TILE_X = 2229
EXTRA_SECTION_TILE_Y = 400
FIRST_BOX_TOP = 9
GAME_REGION = (1920, 0, 1920, 1068)
LEVEL_SCREEN_BOTTOM = 822
LEVEL_SCREEN_LEFT = 2489
LEVEL_SCREEN_RIGHT = 3269
LEVEL_SCREEN_TOP = 303
SCHEDULE_BOTTOM = 897
SCHEDULE_LEFT = 2061
SCHEDULE_RIGHT = 3521
SCHEDULE_TOP = 235
SCROLL_PER_BOX = -268
SERVICE_BOX_HEIGHT = 58
SERVICE_BOX_STRIDE = 69
SERVICE_LIST_BOTTOM = 916
SERVICE_LIST_LEFT = 2067
SERVICE_LIST_RIGHT = 2679
SERVICE_LIST_TOP = 330
TRAIN_BOX_HEIGHT = 482
TRAIN_BOX_LEFT = 3208
TRAIN_BOX_STRIDE = 80
TRAIN_BOX_TOP = 413
TRAIN_BOX_WIDTH = 464
TRAIN_FIRST_Y_OFFSET = 44
TRAIN_SCROLL_PER_BOX = -310
TRAIN_VISIBLE_COUNT = 2

# ── Recomputed derived values ──
BOXES_TO_SCROLL = BOXES_PER_PAGE - OVERLAP_BOXES
SCROLL_AMOUNT = SCROLL_PER_BOX * BOXES_TO_SCROLL
LEVEL_SCREEN_REGION = (LEVEL_SCREEN_LEFT, LEVEL_SCREEN_TOP,
                       LEVEL_SCREEN_RIGHT - LEVEL_SCREEN_LEFT,
                       LEVEL_SCREEN_BOTTOM - LEVEL_SCREEN_TOP)
